### ISSUE TITLE
Hi, I am interested in the repo "https://github.com/awsong/wireguard-go"

### ISSUE THREAD

**Issue by nengc** [awsong/home-config#1]
Hi , I found the repo "https://github.com/awsong/wireguard-go" with the sm2/sm3/sm4. And i checked it out, but something went wrong. 

I am confused about the code below, can you explain it:
![image](https://github.com/awsong/home-config/assets/19792047/d18b434c-ed74-449b-b180-696769eec0bb)

And i rebuild the wireguard-windows using the wireguard-go, but cannot connected the server hosted by the wireguard-go. And i just replaced the sm2.

![image](https://github.com/awsong/home-config/assets/19792047/a4884e68-a2f8-49d3-a005-724bae675557)

https://github.com/awsong/wireguard-go/commit/751631a7d3b6b2fc1e7c7c4fd3297db4e7818d04#diff-ddf1783db09b9601c267e27c63415b1d76385cadb26ff21ac8280efd554f9dd4

Thanks

**Comment by awsong** [comment]
It's a dirty hack, meaning to use a hard coded pubkey when the "key" in config file matches certain value. 

The reason is that SM2 public key size is different from ED25519 and I don't want to waste any effort on config files. This repo only intends to prove that replacing ED25519/Chacha20/Blake2 with SM2/3/4 is doable. If you need to use it you have to adjust further.

**Comment by nengc** [comment]
@awsong tks for your reply. I have resolve the problem and can connect to the server. I modified the wireguard-widows and created a CLI config tool for the linux server.
